# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:53
from __future__ import unicode_literals

from django.db import migrations
import tagging_autocomplete.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160512_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=tagging_autocomplete.models.TagAutocompleteField(blank=True, max_length=255),
        ),
    ]
