# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='figure_one',
            field=models.FileField(blank=True, default='', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure_three',
            field=models.FileField(blank=True, default='', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure_two',
            field=models.FileField(blank=True, default='', null=True, upload_to=b''),
        ),
    ]
