# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20160530_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', null=True, upload_to=b'')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.TextField(default='Table source', max_length=200)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
