# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_images_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tables',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
