# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20160531_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='figure_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='figure_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='figure_two',
        ),
        migrations.RemoveField(
            model_name='question',
            name='latex_figure_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='latex_figure_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='latex_figure_two',
        ),
    ]
