# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_difficulty'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX questions_fulltext_index ON questions_question (question_description)',),
            ('DROP INDEX questions_fulltext_index on questions',)
        )
    ]