# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20160615_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
