# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tagging_autocomplete.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_question_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.TextField(default='Exam name', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('exam_description', models.TextField(default='Description - web/comments only', max_length=200)),
                ('last_edited', models.DateTimeField(default=datetime.datetime.now, verbose_name='date last edited')),
                ('num_edits', models.PositiveIntegerField(default=0)),
                ('exam_author', models.CharField(default='None yet', max_length=200)),
                ('contributing_authors', models.CharField(default='None yet', max_length=200)),
                ('tags', tagging_autocomplete.models.TagAutocompleteField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('questions', models.CommaSeparatedIntegerField(max_length=200)),
            ],
        ),
    ]
