# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20160725_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='footer',
            field=models.TextField(default='%Exam footer', max_length=2000),
        ),
        migrations.AddField(
            model_name='exam',
            name='header',
            field=models.TextField(default='%Exam Header', max_length=2000),
        ),
    ]
