# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20160726_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Exam name', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField(default='Description - web/comments only', max_length=200)),
                ('last_edited', models.DateTimeField(default=datetime.datetime.now, verbose_name='date last edited')),
                ('num_edits', models.PositiveIntegerField(default=0)),
                ('template_author', models.CharField(default='None yet', max_length=200)),
                ('header', models.TextField(default='%Exam Header', max_length=2000)),
                ('footer', models.TextField(default='%Exam footer', max_length=2000)),
            ],
        ),
    ]
